import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ExerciseProvider } from "@/components/context/ExerciseContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="bg-[#0C0D10]">
        <ExerciseProvider>
        <div className="min-h-full flex flex-col mx-4 lg:mx-6">
          <Navbar />
        {children}
        <Footer/>
        
        </div>

        <ToastContainer />
        </ExerciseProvider>
      </body>
    </html>
  );
}
